import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Libre_Bodoni } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { plPL } from '@clerk/localizations';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const libreBodoni = Libre_Bodoni({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-libre-bodoni',
});

export const metadata: Metadata = {
  title: 'Co się dzieje w Polsce',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          navbar:
            '!bg-none !bg-neutral-100/90 dark:!bg-neutral-800/60 backdrop-blur-sm [&_p]:dark:!text-neutral-100 [&_p]:!text-neutral-900 [&_h1]:dark:!text-neutral-100 [&_h1]:!text-neutral-900 [&_button]:dark:!text-neutral-100 [&_button]:!text-neutral-900',
          scrollBox:
            '!bg-neutral-100/90 dark:!bg-neutral-800/60 backdrop-blur-sm [&_p]:dark:!text-neutral-100 [&_p]:!text-neutral-900 [&_h1]:dark:!text-neutral-100 [&_h1]:!text-neutral-900 [&_button]:dark:!text-neutral-100 [&_button]:!text-neutral-900',
          modalCloseButton: 'dark:!text-neutral-100 !text-neutral-900',
          badge:
            '!dark:bg-neutral-700/50 !bg-neutral-600/10 !text-neutral-900 dark:!text-neutral-100 !rounded-full',
          profileSection: '!border-t-neutral-100 dark:!border-t-neutral-900',
        },
      }}
      localization={plPL}
    >
      <html lang="pl">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${libreBodoni.variable} antialiased dark`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
};
export default RootLayout;
